#!/bin/bash

# HiDPI configuration
echo "user_pref(\"layout.css.devPixelsPerPx\", \""$SCALE"\");" > /home/user/.mozilla/firefox/l12mv1bp.main/user.js

# Check id KIOSK is enabled
if [ "$KIOSK_MODE" = "true" ]; then
    KIOSK_FLAG="--kiosk"
else
    KIOSK_FLAG=""
fi

# Start firefox
DISPLAY=":1" firefox -P main $KIOSK_FLAG $START_URL &
