#!/bin/bash

# Set firefox configuration
cat > /home/user/.mozilla/firefox/l12mv1bp.main/user.js << EOL
user_pref("layout.css.devPixelsPerPx", "${SCALE}");
// Disable recovery last session
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.resume_session_once", false);
user_pref("browser.sessionstore.resuming_after_os_restart", false);
user_pref("browser.sessionstore.max_resumed_crashes", 0);
user_pref("browser.sessionstore.max_tabs_undo", 0);
// Set default page
user_pref("browser.startup.homepage", "${START_URL}");
user_pref("browser.startup.page", 1);
EOL

# Check if KIOSK is enabled by the user
if [ "$KIOSK_MODE" = "true" ]; then
    KIOSK_FLAG="--kiosk"
else
    KIOSK_FLAG=""
fi

# Start firefox
DISPLAY=":1" firefox -P main $KIOSK_FLAG --no-remote --new-instance $START_URL &
